#!/usr/bin/env python3
"""Convert single-frame snapshot HDF5s into Ctrl-World's per-episode dataset layout.

Each input HDF5 (``snapshot_N.hdf5``) contains a single timestep:
    data/demo_<N>/obs/{agent_view, exterior_2, exterior_3, wrist}  # 720x1280 uint8
    data/demo_<N>/state/{EE_POS(3), EE_EULER(3), GRIPPER(1), JOINT_POS(7)}

We turn each snapshot into a Ctrl-World "episode" that ``rollout_interact_pi.py``
can consume: 3 videos (exterior_1, exterior_2, wrist) of length ``--repeat`` with
the snapshot frame replicated, plus an annotation JSON whose ``states``/``joints``
are also tiled. ``rollout_interact_pi.py`` only reads ``states[0]``, ``joints[0]``
and the first frame of each video; the rest of the rollout is generated by
pi0.5 + Ctrl-World. We still tile to satisfy upstream length checks.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import cv2
import h5py
import numpy as np


_DEFAULT_VIEW_KEYS = ("agent_view", "exterior_2", "wrist")


def _snapshot_id(path: Path) -> int:
    match = re.fullmatch(r"snapshot_(\d+)\.hdf5", path.name)
    if not match:
        raise ValueError(f"Unexpected snapshot filename: {path}")
    return int(match.group(1))


def _convert_gripper(gripper: np.ndarray, mode: str, scale: float) -> np.ndarray:
    if mode == "raw":
        converted = gripper
    elif mode == "invert":
        converted = 1.0 - gripper
    elif mode == "invert_scale":
        converted = (1.0 - gripper) * scale
    elif mode == "scale":
        converted = gripper * scale
    else:
        raise ValueError(f"Unknown gripper mode: {mode}")
    return np.clip(converted, 0.0, scale).astype(np.float32)


def _read_snapshot(path: Path, view_keys: tuple[str, ...], gripper_mode: str, gripper_scale: float) -> dict:
    with h5py.File(path, "r") as h5:
        demo_names = list(h5["data"].keys())
        if len(demo_names) != 1:
            raise ValueError(f"Expected one demo in {path}, found {demo_names}")
        demo = h5["data"][demo_names[0]]
        obs = demo["obs"]
        state = demo["state"]

        missing = [k for k in view_keys if k not in obs]
        if missing:
            raise KeyError(f"{path}: missing obs views {missing} (have {list(obs.keys())})")

        frames = [np.asarray(obs[k][...]) for k in view_keys]
        ee_pos = np.asarray(state["EE_POS"][...], dtype=np.float32).reshape(-1)
        ee_euler = np.asarray(state["EE_EULER"][...], dtype=np.float32).reshape(-1)
        gripper_raw = np.asarray(state["GRIPPER"][...], dtype=np.float32).reshape(-1)
        joint_pos = np.asarray(state["JOINT_POS"][...], dtype=np.float32).reshape(-1)

    if ee_pos.shape != (3,):
        raise ValueError(f"{path}: EE_POS shape {ee_pos.shape} != (3,)")
    if ee_euler.shape != (3,):
        raise ValueError(f"{path}: EE_EULER shape {ee_euler.shape} != (3,)")
    if gripper_raw.shape != (1,):
        raise ValueError(f"{path}: GRIPPER shape {gripper_raw.shape} != (1,)")
    if joint_pos.shape != (7,):
        raise ValueError(f"{path}: JOINT_POS shape {joint_pos.shape} != (7,)")

    gripper = _convert_gripper(gripper_raw, gripper_mode, gripper_scale)
    state7 = np.concatenate([ee_pos, ee_euler, gripper], axis=0).astype(np.float32)
    joint8 = np.concatenate([joint_pos, gripper], axis=0).astype(np.float32)

    return {
        "frames": frames,
        "state7": state7,
        "joint8": joint8,
        "ee_pos": ee_pos,
        "joint_pos": joint_pos,
        "gripper": gripper,
        "demo_name": demo_names[0],
    }


def _write_repeated_video(frame: np.ndarray, output_path: Path, width: int, height: int, fps: float, repeat: int) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    writer = cv2.VideoWriter(
        str(output_path),
        cv2.VideoWriter_fourcc(*"mp4v"),
        fps,
        (width, height),
    )
    if not writer.isOpened():
        raise RuntimeError(f"Could not open video writer for {output_path}")

    # frame is RGB (from HDF5); cv2 wants BGR.
    resized = cv2.resize(frame, (width, height), interpolation=cv2.INTER_AREA)
    bgr = cv2.cvtColor(resized, cv2.COLOR_RGB2BGR)
    for _ in range(repeat):
        writer.write(bgr)
    writer.release()


def convert(args: argparse.Namespace) -> None:
    source_dir = Path(args.source_dir)
    output_dir = Path(args.output_dir)
    view_keys = tuple(v.strip() for v in args.views.split(",") if v.strip())
    if len(view_keys) != 3:
        raise ValueError("--views must list exactly 3 HDF5 obs keys (exterior_1, exterior_2, wrist)")

    snapshot_paths = sorted(source_dir.glob("snapshot_*.hdf5"), key=_snapshot_id)
    if not snapshot_paths:
        raise RuntimeError(f"No snapshot_*.hdf5 found in {source_dir}")
    if args.limit:
        snapshot_paths = snapshot_paths[: args.limit]

    annotation_dir = output_dir / "annotation" / "val"
    annotation_dir.mkdir(parents=True, exist_ok=True)

    val_ids: list[str] = []
    report = []
    for snap_path in snapshot_paths:
        snap_id = _snapshot_id(snap_path)
        episode_id = f"{snap_id:04d}"
        data = _read_snapshot(snap_path, view_keys, args.gripper_mode, args.gripper_scale)

        for view_idx, frame in enumerate(data["frames"]):
            _write_repeated_video(
                frame=frame,
                output_path=output_dir / "videos" / "val" / episode_id / f"{view_idx}.mp4",
                width=args.width,
                height=args.height,
                fps=args.fps,
                repeat=args.repeat,
            )

        state_tiled = np.tile(data["state7"], (args.repeat, 1))
        joint_tiled = np.tile(data["joint8"], (args.repeat, 1))
        zeros7 = np.zeros((args.repeat, 7), dtype=np.float32)
        zeros1 = data["gripper"][None, :].repeat(args.repeat, axis=0)

        annotation = {
            "texts": [args.default_instruction],
            "episode_id": episode_id,
            "success": 0,
            "video_length": args.repeat,
            "state_length": args.repeat,
            "raw_length": 1,
            "videos": [{"video_path": f"videos/val/{episode_id}/{i}.mp4"} for i in range(3)],
            "latent_videos": [
                {"latent_video_path": f"latent_videos/val/{episode_id}/{i}.pt"} for i in range(3)
            ],
            "states": state_tiled.tolist(),
            "joints": joint_tiled.tolist(),
            "observation.state.cartesian_position": np.tile(data["ee_pos"], (args.repeat, 1)).tolist(),
            "observation.state.joint_position": np.tile(data["joint_pos"], (args.repeat, 1)).tolist(),
            "observation.state.gripper_position": data["gripper"][None, :].repeat(args.repeat, axis=0).tolist(),
            "action.cartesian_position": zeros7.tolist(),
            "action.joint_position": zeros7[:, :7].tolist(),
            "action.gripper_position": zeros1.tolist(),
            "action.joint_velocity": zeros7[:, :7].tolist(),
            "metadata": {
                "source_hdf5": str(snap_path),
                "source_demo_group": data["demo_name"],
                "source_view_keys": list(view_keys),
                "source_layout": "single-frame snapshot replicated to length",
                "repeat": args.repeat,
                "gripper_mode": args.gripper_mode,
                "gripper_scale": args.gripper_scale,
            },
        }

        with (annotation_dir / f"{episode_id}.json").open("w") as f:
            json.dump(annotation, f, indent=2)

        val_ids.append(episode_id)
        report.append({"episode_id": episode_id, "source_hdf5": str(snap_path)})

    meta_dir = output_dir / "meta"
    meta_dir.mkdir(parents=True, exist_ok=True)
    with (meta_dir / "val_ids.json").open("w") as f:
        json.dump(val_ids, f, indent=2)
    with (meta_dir / "conversion_report.json").open("w") as f:
        json.dump(report, f, indent=2)

    print(f"Wrote {len(val_ids)} Ctrl-World snapshot episodes to {output_dir}")
    print(f"  views = {view_keys}, repeat = {args.repeat}, instruction = {args.default_instruction!r}")
    print(f"  val_ids: {val_ids[0]} .. {val_ids[-1]}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Convert snapshot HDF5s to Ctrl-World dataset layout.")
    parser.add_argument("--source_dir", required=True, help="Directory containing snapshot_N.hdf5 files.")
    parser.add_argument("--output_dir", required=True, help="Ctrl-World dataset root to write into.")
    parser.add_argument("--default_instruction", required=True, help="Instruction string used for all snapshots in this zip.")
    parser.add_argument("--views", default=",".join(_DEFAULT_VIEW_KEYS), help="Comma-separated HDF5 obs keys to use as (exterior_1, exterior_2, wrist).")
    parser.add_argument("--width", type=int, default=320)
    parser.add_argument("--height", type=int, default=192)
    parser.add_argument("--fps", type=float, default=5.0)
    parser.add_argument("--repeat", type=int, default=100, help="Frames to replicate per video; must exceed pred_step*interact_num+8 (default Ctrl-World pickplace is 83).")
    parser.add_argument("--gripper_mode", choices=["raw", "invert", "scale", "invert_scale"], default="invert")
    parser.add_argument("--gripper_scale", type=float, default=0.75)
    parser.add_argument("--limit", type=int, default=None, help="Optional cap on number of snapshots (smoke testing).")
    args = parser.parse_args()
    convert(args)


if __name__ == "__main__":
    main()
