"""Checkpoint source→dest mapping for real-robot portfolio organization."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

Task = Literal["cube", "tomato"]
Method = Literal["lora", "full"]


@dataclass(frozen=True)
class CheckpointEntry:
    task: Task
    source_exp: str
    source_step: int
    dest_name: str
    method: Method
    augmentation: bool
    loss_threshold: float | None
    prompt: str
    recommended_for_robot: bool
    rationale: str = ""


CUBE_PROMPT = "put the orange block in the blue bowl"
TOMATO_PROMPT = "Pick the tomato"
TOMATO_BOWL_PROMPT = "pick the tomato and place it in the blue bowl"

CHECKPOINT_ENTRIES: tuple[CheckpointEntry, ...] = (
    # Cube baseline
    CheckpointEntry(
        task="cube",
        source_exp="cube_c16_lora_v0",
        source_step=500,
        dest_name="lora_v0_step500",
        method="lora",
        augmentation=False,
        loss_threshold=0.012,
        prompt=CUBE_PROMPT,
        recommended_for_robot=True,
        rationale="reference baseline",
    ),
    # cube_c16_lora_v1_noaug
    CheckpointEntry(
        task="cube",
        source_exp="cube_c16_lora_v1_noaug",
        source_step=175,
        dest_name="lora_noaug_thr010_step175",
        method="lora",
        augmentation=False,
        loss_threshold=0.10,
        prompt=CUBE_PROMPT,
        recommended_for_robot=False,
    ),
    CheckpointEntry(
        task="cube",
        source_exp="cube_c16_lora_v1_noaug",
        source_step=200,
        dest_name="lora_noaug_thr004_step200",
        method="lora",
        augmentation=False,
        loss_threshold=0.04,
        prompt=CUBE_PROMPT,
        recommended_for_robot=True,
        rationale="early-checkpoint hypothesis",
    ),
    CheckpointEntry(
        task="cube",
        source_exp="cube_c16_lora_v1_noaug",
        source_step=400,
        dest_name="lora_noaug_thr0015_step400",
        method="lora",
        augmentation=False,
        loss_threshold=0.015,
        prompt=CUBE_PROMPT,
        recommended_for_robot=False,
    ),
    # cube_c16_lora_v1_aug
    CheckpointEntry(
        task="cube",
        source_exp="cube_c16_lora_v1_aug",
        source_step=175,
        dest_name="lora_aug_thr010_step175",
        method="lora",
        augmentation=True,
        loss_threshold=0.10,
        prompt=CUBE_PROMPT,
        recommended_for_robot=True,
        rationale="max generalization",
    ),
    CheckpointEntry(
        task="cube",
        source_exp="cube_c16_lora_v1_aug",
        source_step=200,
        dest_name="lora_aug_thr004_step200",
        method="lora",
        augmentation=True,
        loss_threshold=0.04,
        prompt=CUBE_PROMPT,
        recommended_for_robot=True,
        rationale="likely best overall",
    ),
    CheckpointEntry(
        task="cube",
        source_exp="cube_c16_lora_v1_aug",
        source_step=475,
        dest_name="lora_aug_thr0015_step475",
        method="lora",
        augmentation=True,
        loss_threshold=0.015,
        prompt=CUBE_PROMPT,
        recommended_for_robot=False,
        rationale="LoRA late + aug: bracket right side",
    ),
    # cube_c16_full_v1_noaug
    CheckpointEntry(
        task="cube",
        source_exp="cube_c16_full_v1_noaug",
        source_step=175,
        dest_name="full_noaug_thr010_step175",
        method="full",
        augmentation=False,
        loss_threshold=0.10,
        prompt=CUBE_PROMPT,
        recommended_for_robot=False,
    ),
    CheckpointEntry(
        task="cube",
        source_exp="cube_c16_full_v1_noaug",
        source_step=225,
        dest_name="full_noaug_thr004_step225",
        method="full",
        augmentation=False,
        loss_threshold=0.04,
        prompt=CUBE_PROMPT,
        recommended_for_robot=True,
        rationale="isolates aug effect",
    ),
    CheckpointEntry(
        task="cube",
        source_exp="cube_c16_full_v1_noaug",
        source_step=625,
        dest_name="full_noaug_thr0015_step625",
        method="full",
        augmentation=False,
        loss_threshold=0.015,
        prompt=CUBE_PROMPT,
        recommended_for_robot=False,
    ),
    # cube_c16_full_v1_aug
    CheckpointEntry(
        task="cube",
        source_exp="cube_c16_full_v1_aug",
        source_step=175,
        dest_name="full_aug_thr010_step175",
        method="full",
        augmentation=True,
        loss_threshold=0.10,
        prompt=CUBE_PROMPT,
        recommended_for_robot=False,
        rationale="full FT early + aug: full FT early stop",
    ),
    CheckpointEntry(
        task="cube",
        source_exp="cube_c16_full_v1_aug",
        source_step=250,
        dest_name="full_aug_thr004_step250",
        method="full",
        augmentation=True,
        loss_threshold=0.04,
        prompt=CUBE_PROMPT,
        recommended_for_robot=True,
        rationale="extra capacity + regularized",
    ),
    CheckpointEntry(
        task="cube",
        source_exp="cube_c16_full_v1_aug",
        source_step=650,
        dest_name="full_aug_thr0015_step650",
        method="full",
        augmentation=True,
        loss_threshold=0.015,
        prompt=CUBE_PROMPT,
        recommended_for_robot=False,
    ),
    # tomato_t24_lora_v1_noaug
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_lora_v1_noaug",
        source_step=175,
        dest_name="lora_noaug_thr010_step175",
        method="lora",
        augmentation=False,
        loss_threshold=0.10,
        prompt=TOMATO_PROMPT,
        recommended_for_robot=False,
    ),
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_lora_v1_noaug",
        source_step=200,
        dest_name="lora_noaug_thr004_step200",
        method="lora",
        augmentation=False,
        loss_threshold=0.04,
        prompt=TOMATO_PROMPT,
        recommended_for_robot=True,
        rationale="early-checkpoint hypothesis",
    ),
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_lora_v1_noaug",
        source_step=350,
        dest_name="lora_noaug_thr0015_step350",
        method="lora",
        augmentation=False,
        loss_threshold=0.015,
        prompt=TOMATO_PROMPT,
        recommended_for_robot=False,
        rationale="near-converged baseline (superseded by _bowl retrain)",
    ),
    # tomato_t24_lora_v1_aug
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_lora_v1_aug",
        source_step=175,
        dest_name="lora_aug_thr010_step175",
        method="lora",
        augmentation=True,
        loss_threshold=0.10,
        prompt=TOMATO_PROMPT,
        recommended_for_robot=True,
        rationale="max generalization",
    ),
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_lora_v1_aug",
        source_step=200,
        dest_name="lora_aug_thr004_step200",
        method="lora",
        augmentation=True,
        loss_threshold=0.04,
        prompt=TOMATO_PROMPT,
        recommended_for_robot=False,
        rationale="likely best overall (superseded by _bowl retrain)",
    ),
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_lora_v1_aug",
        source_step=425,
        dest_name="lora_aug_thr0015_step425",
        method="lora",
        augmentation=True,
        loss_threshold=0.015,
        prompt=TOMATO_PROMPT,
        recommended_for_robot=False,
        rationale="LoRA late + aug: bracket right side",
    ),
    # tomato_t24_full_v1_noaug
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_full_v1_noaug",
        source_step=175,
        dest_name="full_noaug_thr010_step175",
        method="full",
        augmentation=False,
        loss_threshold=0.10,
        prompt=TOMATO_PROMPT,
        recommended_for_robot=False,
    ),
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_full_v1_noaug",
        source_step=225,
        dest_name="full_noaug_thr004_step225",
        method="full",
        augmentation=False,
        loss_threshold=0.04,
        prompt=TOMATO_PROMPT,
        recommended_for_robot=True,
        rationale="isolates aug effect",
    ),
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_full_v1_noaug",
        source_step=600,
        dest_name="full_noaug_thr0015_step600",
        method="full",
        augmentation=False,
        loss_threshold=0.015,
        prompt=TOMATO_PROMPT,
        recommended_for_robot=False,
    ),
    # tomato_t24_full_v1_aug
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_full_v1_aug",
        source_step=175,
        dest_name="full_aug_thr010_step175",
        method="full",
        augmentation=True,
        loss_threshold=0.10,
        prompt=TOMATO_PROMPT,
        recommended_for_robot=False,
        rationale="full FT early + aug: full FT early stop",
    ),
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_full_v1_aug",
        source_step=225,
        dest_name="full_aug_thr004_step225",
        method="full",
        augmentation=True,
        loss_threshold=0.04,
        prompt=TOMATO_PROMPT,
        recommended_for_robot=False,
        rationale="extra capacity + regularized (superseded by _bowl retrain)",
    ),
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_full_v1_aug",
        source_step=650,
        dest_name="full_aug_thr0015_step650",
        method="full",
        augmentation=True,
        loss_threshold=0.015,
        prompt=TOMATO_PROMPT,
        recommended_for_robot=False,
    ),
    # Tomato bowl-prompt retrain (recommended #4 / #6 replacement)
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_lora_bowl_aug",
        source_step=200,
        dest_name="lora_aug_thr004_step200_bowl",
        method="lora",
        augmentation=True,
        loss_threshold=0.04,
        prompt=TOMATO_BOWL_PROMPT,
        recommended_for_robot=False,
        rationale="likely best overall (bowl prompt; optional vs #3)",
    ),
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_full_bowl_aug",
        source_step=225,
        dest_name="full_aug_thr004_step225_bowl",
        method="full",
        augmentation=True,
        loss_threshold=0.04,
        prompt=TOMATO_BOWL_PROMPT,
        recommended_for_robot=True,
        rationale="recommended #4: full FT + aug (bowl prompt)",
    ),
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_lora_bowl_noaug",
        source_step=350,
        dest_name="lora_noaug_thr0015_step350_bowl",
        method="lora",
        augmentation=False,
        loss_threshold=0.015,
        prompt=TOMATO_BOWL_PROMPT,
        recommended_for_robot=True,
        rationale="recommended #6: near-converged LoRA (bowl prompt)",
    ),
    # Cube agent_view retrain (LoRA, no aug). policy_obs_exterior was swapped
    # from exterior_3 -> agent_view; wrist unchanged.
    CheckpointEntry(
        task="cube",
        source_exp="cube_c16_lora_agent_view_noaug",
        source_step=175,
        dest_name="lora_agent_view_noaug_thr010_step175",
        method="lora",
        augmentation=False,
        loss_threshold=0.10,
        prompt=CUBE_PROMPT,
        recommended_for_robot=False,
        rationale="agent_view exterior (LoRA, thr=0.10)",
    ),
    CheckpointEntry(
        task="cube",
        source_exp="cube_c16_lora_agent_view_noaug",
        source_step=200,
        dest_name="lora_agent_view_noaug_thr004_step200",
        method="lora",
        augmentation=False,
        loss_threshold=0.04,
        prompt=CUBE_PROMPT,
        recommended_for_robot=True,
        rationale="agent_view exterior (LoRA sweet spot)",
    ),
    CheckpointEntry(
        task="cube",
        source_exp="cube_c16_lora_agent_view_noaug",
        source_step=400,
        dest_name="lora_agent_view_noaug_thr0015_step400",
        method="lora",
        augmentation=False,
        loss_threshold=0.015,
        prompt=CUBE_PROMPT,
        recommended_for_robot=True,
        rationale="agent_view exterior (near-converged LoRA)",
    ),
    # Tomato agent_view retrain (LoRA, no aug, bowl prompt). policy_obs_exterior
    # was swapped from exterior_3 -> agent_view; wrist unchanged.
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_lora_agent_view_noaug",
        source_step=175,
        dest_name="lora_agent_view_noaug_thr010_step175_bowl",
        method="lora",
        augmentation=False,
        loss_threshold=0.10,
        prompt=TOMATO_BOWL_PROMPT,
        recommended_for_robot=False,
        rationale="agent_view exterior (LoRA, bowl prompt, thr=0.10)",
    ),
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_lora_agent_view_noaug",
        source_step=200,
        dest_name="lora_agent_view_noaug_thr004_step200_bowl",
        method="lora",
        augmentation=False,
        loss_threshold=0.04,
        prompt=TOMATO_BOWL_PROMPT,
        recommended_for_robot=True,
        rationale="agent_view exterior (LoRA sweet spot, bowl prompt)",
    ),
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_lora_agent_view_noaug",
        source_step=375,
        dest_name="lora_agent_view_noaug_thr0015_step375_bowl",
        method="lora",
        augmentation=False,
        loss_threshold=0.015,
        prompt=TOMATO_BOWL_PROMPT,
        recommended_for_robot=True,
        rationale="agent_view exterior (near-converged LoRA, bowl prompt)",
    ),
    # Cube agent_view retrain (full FT, no aug). policy_obs_exterior was
    # swapped from exterior_3 -> agent_view; wrist unchanged.
    CheckpointEntry(
        task="cube",
        source_exp="cube_c16_full_agent_view_noaug",
        source_step=175,
        dest_name="full_agent_view_noaug_thr010_step175",
        method="full",
        augmentation=False,
        loss_threshold=0.10,
        prompt=CUBE_PROMPT,
        recommended_for_robot=False,
        rationale="agent_view exterior (full FT, thr=0.10)",
    ),
    CheckpointEntry(
        task="cube",
        source_exp="cube_c16_full_agent_view_noaug",
        source_step=225,
        dest_name="full_agent_view_noaug_thr004_step225",
        method="full",
        augmentation=False,
        loss_threshold=0.04,
        prompt=CUBE_PROMPT,
        recommended_for_robot=True,
        rationale="agent_view exterior (full FT sweet spot)",
    ),
    CheckpointEntry(
        task="cube",
        source_exp="cube_c16_full_agent_view_noaug",
        source_step=625,
        dest_name="full_agent_view_noaug_thr0015_step625",
        method="full",
        augmentation=False,
        loss_threshold=0.015,
        prompt=CUBE_PROMPT,
        recommended_for_robot=True,
        rationale="agent_view exterior (near-converged full FT)",
    ),
    # Tomato agent_view retrain (full FT, no aug, bowl prompt). policy_obs_exterior
    # was swapped from exterior_3 -> agent_view; wrist unchanged.
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_full_agent_view_noaug",
        source_step=175,
        dest_name="full_agent_view_noaug_thr010_step175_bowl",
        method="full",
        augmentation=False,
        loss_threshold=0.10,
        prompt=TOMATO_BOWL_PROMPT,
        recommended_for_robot=False,
        rationale="agent_view exterior (full FT, bowl prompt, thr=0.10)",
    ),
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_full_agent_view_noaug",
        source_step=225,
        dest_name="full_agent_view_noaug_thr004_step225_bowl",
        method="full",
        augmentation=False,
        loss_threshold=0.04,
        prompt=TOMATO_BOWL_PROMPT,
        recommended_for_robot=True,
        rationale="agent_view exterior (full FT sweet spot, bowl prompt)",
    ),
    CheckpointEntry(
        task="tomato",
        source_exp="tomato_t24_full_agent_view_noaug",
        source_step=625,
        dest_name="full_agent_view_noaug_thr0015_step625_bowl",
        method="full",
        augmentation=False,
        loss_threshold=0.015,
        prompt=TOMATO_BOWL_PROMPT,
        recommended_for_robot=True,
        rationale="agent_view exterior (near-converged full FT, bowl prompt)",
    ),
    # Hand-collected trajectories (exterior_2 + wrist, 30 cube / 24 tomato demos)
    CheckpointEntry(
        task="cube",
        source_exp="handcollected_cube_lora_aug",
        source_step=225,
        dest_name="lora_aug_thr004_step225_hand",
        method="lora",
        augmentation=True,
        loss_threshold=0.04,
        prompt=CUBE_PROMPT,
        recommended_for_robot=False,
        rationale="hand-collected demos; exterior_2 + wrist",
    ),
    CheckpointEntry(
        task="tomato",
        source_exp="handcollected_tomato_lora_aug",
        source_step=200,
        dest_name="lora_aug_thr004_step200_hand_bowl",
        method="lora",
        augmentation=True,
        loss_threshold=0.04,
        prompt=TOMATO_BOWL_PROMPT,
        recommended_for_robot=False,
        rationale="hand-collected demos; exterior_2 + wrist; bowl prompt",
    ),
)

V1_SOURCE_EXPS: frozenset[str] = frozenset(
    {
        "cube_c16_lora_v1_noaug",
        "cube_c16_lora_v1_aug",
        "cube_c16_full_v1_noaug",
        "cube_c16_full_v1_aug",
        "tomato_t24_lora_v1_noaug",
        "tomato_t24_lora_v1_aug",
        "tomato_t24_full_v1_noaug",
        "tomato_t24_full_v1_aug",
    }
)
